import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Certification | Alliance Group LLC',
  description: 'Generated by create next app',
};

const Certification = () => {
  return <h2>Certification</h2>;
};
export default Certification;
