import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Careers | Alliance Group LLC',
  description: 'Generated by create next app',
};

const Careers = () => {
  return <h2>Careers</h2>;
};
export default Careers;
