import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Services | Alliance Group LLC',
  description: 'Generated by create next app',
};

const Services = () => {
  return <h2>services</h2>;
};
export default Services;
