import { Metadata } from 'next';
import { getIntl } from 'lib/intl';
export const metadata: Metadata = {
  title: 'Gallery | Alliance Group LLC',
  description: 'Generated by create next app',
};

import styles from './Gallery.module.scss';

const getMediaFromInstagram = async () => {
  const res = await fetch('https://api.example.com/...', {
    next: { revalidate: 86400 },
  });
  if (!res.ok) {
    throw new Error('Failed to fetch data');
  }
  return res.json();
};

type IProps = {
  params: { locale: string };
};

const Gallery = async ({ params: { locale } }: IProps) => {
  const feed = await getMediaFromInstagram();
  console.log(feed);
  // const intl = await getIntl(locale);

  return <h2>Gallery</h2>;
};
export default Gallery;
