'use client';

import { Metadata } from 'next';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Admin | Alliance Group',
  description: 'Generated by create next app',
};

const Admin = () => {
  const router = useRouter();
  useEffect(() => {
    router.push('/admin/login');
  }, [router]);
  return <></>;
};
export default Admin;
