import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Products-Services | Alliance Group LLC',
  description: 'Generated by create next app',
};
import styles from './ProductsServices.module.scss';
import {
  getAllProducts,
  getAllServices,
  getDataProductsServicesFromFirestore,
} from '@/firebase/getData';
import HeroSection from 'components/heroSection/HeroSection';
import Content from 'components/content/Content';

import ProductsServicesList from 'components/productsServicesList/ProductsServicesList';

type IProps = {
  params: { locale: string };
};

const ProductsServices = async ({ params: { locale } }: IProps) => {
  const data = await getDataProductsServicesFromFirestore();
  // console.log('page products-services', data);
  const listAllProducts = await getAllProducts();
  // console.log('Page ProductsServices', listAllProducts);
  const listAllServices = await getAllServices();
  // console.log('Page ProductsServices', listAllServices);
  return (
    <>
      {locale === 'uk' && (
        <HeroSection
          backgroundImage={data?.backgroundImageDesktop}
          title={data?.titleUK}
          subtitle={data?.subtitleUK}
          initialAnimation={-3600}
        />
      )}
      {locale === 'en' && (
        <HeroSection
          backgroundImage={data?.backgroundImageDesktop}
          title={data?.titleEN}
          subtitle={data?.subtitleEN}
          initialAnimation={-3500}
        />
      )}
      {locale === 'tr' && (
        <HeroSection
          backgroundImage={data?.backgroundImageDesktop}
          title={data?.titleTR}
          subtitle={data?.subtitleTR}
          initialAnimation={-2850}
        />
      )}
      <section className={styles.container}>
        {data?.textUK && locale === 'uk' && (
          <div className={styles.contentWrapper}>
            <Content content={data?.textUK} />
          </div>
        )}
        {data?.textEN && locale === 'en' && (
          <div className={styles.contentWrapper}>
            <Content content={data?.textEN} />
          </div>
        )}
        {data?.textTR && locale === 'tr' && (
          <div className={styles.contentWrapper}>
            <Content content={data?.textTR} />
          </div>
        )}

        <ProductsServicesList
          products={listAllProducts}
          services={listAllServices}
          locale={locale}
        />
      </section>
    </>
  );
};
export default ProductsServices;
