import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Our Partners | Alliance Group LLC',
  description: 'Generated by create next app',
};

const Partners = () => {
  return <h2>Our Partners</h2>;
};
export default Partners;
