import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Products-Services | Alliance Group LLC',
  description: 'Generated by create next app',
};

const ProductsServices = () => {
  return <h2>Products/Services</h2>;
};
export default ProductsServices;
