import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contacts | Alliance Group LLC',
  description: 'Generated by create next app',
};

const Contacts = () => {
  return <h2>Contacts</h2>;
};
export default Contacts;
