import { Metadata } from 'next';
import { AboutUsType } from 'types/dataTypeForFirebase';
import { getDataFromFirestore } from '@/firebase/getData';

export const metadata: Metadata = {
  title: 'About Us | Alliance Group LLC',
  description: 'Generated by create next app',
};

// export async function getStaticProps() {
//   const data = await getDataFromFirestore('about-us');
//   console.log('Props', data);
//   return {
//     props: {
//       data,
//     },
//   };
// }

// export async function generateStaticParams(): Promise<any> {
//   const data = await getDataFromFirestore('about-us');
//   console.log('Props', data);
//   return {
//     props: {
//       data,
//     },
//   };
// }

export const dynamic = 'force-dynamic';
// export const revalidate = 30;
export const fetchCache = 'default-cache';
export const runtime = 'nodejs';
export const preferredRegion = 'auto';

const AboutUs = async () => {
  const data = await getDataFromFirestore('about-us');
  console.log('page about-us', data?.title);
  return <h2>{data?.title}</h2>;
};
export default AboutUs;
