import { Metadata } from 'next';

import { getDataFromFirestore } from '@/firebase/getData';
import Image from 'next/image';
// import TiptapContent from 'components/Tiptap/TipTapContent';
import Content from 'components/content/Content';

export const metadata: Metadata = {
  title: 'About Us | Alliance Group LLC',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';
// export const revalidate = 30;
export const fetchCache = 'default-cache';
export const runtime = 'nodejs';
export const preferredRegion = 'auto';

const AboutUs = async () => {
  const data = await getDataFromFirestore('about-us');
  console.log('page about-us', data);
  return (
    <>
      <h2>{data?.title}</h2>
      {data?.imageURL && (
        <Image
          src={data?.imageURL}
          width={150}
          height={150}
          alt="The photo download"
        />
      )}
      {data?.content && <Content content={data?.content} />}
    </>
  );
};
export default AboutUs;
