import 'app/globals.scss';
import { raleway } from '@/fonts';
import Header from 'components/header/Header';
import Footer from 'components/footer/Footer';
import styles from './layout.module.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Alliance Group LLC',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={raleway.className}>
      <body className={styles.body}>
        <Header />
        <main className={styles.container}>{children}</main>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
