import 'app/globals.scss';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import Header from 'components/header/Header';
import Footer from 'components/footer/Footer';
import styles from './layout.module.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Alliance Group LLC',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ display: 'flex', flexDirection: 'column' }}
      >
        <Header />
        <main className={styles.container}>{children}</main>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
