import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Main | Alliance Group LLC',
  description: 'Generated by create next app',
};
import { getDataHomePageFromFirestore } from '@/firebase/getData';

import styles from './page.module.scss';
const Home = async () => {
  const data = await getDataHomePageFromFirestore();
  console.log('page home-page', data);

  return (
    <section
      style={{
        backgroundColor: '#5F3918',
        backgroundImage: `url(${data?.imageURL})`,
      }}
      className={styles.hero}
    >
      <div className={styles.wrapperContent}></div>
      <div className={styles.companyName}>ALLIANCE</div>
      <div className={styles.secondCompanyName}>Group LLC™</div>
    </section>
  );
};
export default Home;
