import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Main | Alliance Group LLC',
  description: 'Generated by create next app',
};
import { getDataHomePageFromFirestore } from '@/firebase/getData';

export const revalidate = 18000;

import styles from './page.module.scss';
import HeroContent from 'components/heroContent/HeroContent';
import AnimationHero from 'components/animationHero/AnimationHero';

import BackgroundImage from 'components/backgroundImage/BackgroundImage';

const Home = async () => {
  const data = await getDataHomePageFromFirestore();
  // console.log('page home-page', data);

  return (
    <section className={styles.hero}>
      {data?.backgroundImageDesktop && (
        <BackgroundImage imageUrl={data?.backgroundImageDesktop} />
      )}

      {data && (
        <>
          <HeroContent title={data.title} subtitle={data.subtitle} />

          <AnimationHero title={data.title} />
        </>
      )}
    </section>
  );
};
export default Home;
