import Image from 'next/image';
import styles from './page.module.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Main | Alliance Group LLC',
  description: 'Generated by create next app',
};

const Home = () => {
  return <h1>Alliance Group LLC</h1>;
};
export default Home;
