'use client';

import SideBar from 'components/sideBar/SideBar';
import { useAuthContex } from 'context/AuthContex';
import { useRouter } from 'next/navigation';
// import { Metadata } from 'next';
import { useEffect } from 'react';
import { logout } from '@/firebase/logout';

// export const metadata: Metadata = {
//   title: 'Dashboard | Alliance Group',
//   description: 'Generated by create next app',
// };

const Dashboard = () => {
  const user = useAuthContex();
  const router = useRouter();

  useEffect(() => {
    if (user === null) router.push('/admin/login');
  }, [user, router]);

  const handleClick = () => {
    logout();
    router.push('/');
  };
  if (user === null) return;
  return (
    <>
      <SideBar />
      <h2>Dashboard</h2>
      <button type="button" onClick={handleClick}>
        logout
      </button>
    </>
  );
};
export default Dashboard;
