import SideBar from 'components/sideBar/SideBar';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard | Alliance Group',
  description: 'Generated by create next app',
};

const Dashboard = () => {
  return (
    <>
      <SideBar />
      <h2>Dashboard</h2>
    </>
  );
};
export default Dashboard;
