import 'app/globals.scss';
import { Inter } from 'next/font/google';
import { AuthContexProvider } from 'context/AuthContex';

const inter = Inter({ subsets: ['latin'] });
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Alliance Group',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <AuthContexProvider>{children}</AuthContexProvider>
        </main>
      </body>
    </html>
  );
};
export default RootLayout;
