import 'app/globals.scss';
import { raleway } from '../../styles/fonts';
import { AuthContexProvider } from 'context/AuthContex';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Alliance Group',
  description: 'Generated by create next app',
};
import styles from './layout.module.scss';
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="uk" className={raleway.className}>
      <body className={styles.container}>
        <main>
          <AuthContexProvider>{children}</AuthContexProvider>
        </main>
      </body>
    </html>
  );
};
export default RootLayout;
